# Generated by Django 5.2.17 on 2026-09-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("projects", "0002_projectuserstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="drive_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drive_projects",
                to="integrations.oauthaccount",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drive_folder_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="drive_share_with_members",
            field=models.BooleanField(default=False),
        ),
    ]
