# Generated by Django 5.2.17 on 2026-09-22 05:17

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_projectuserstate"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("document", "PDF / document"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("to_validate", "À valider"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="projects.project",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="assets", to="workspaces.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("to_validate", "À valider"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("to_validate", "À valider"),
                            ("approved", "Validé"),
                            ("rejected", "Refusé"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="files.asset",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=120)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        upload_to=apps.files.models.version_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.CharField(blank=True, max_length=200)),
                ("drive_file_id", models.CharField(blank=True, max_length=200)),
                ("drive_meta", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="files.asset",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="AssetDerivative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stream_mp3", "MP3 128 kbps"),
                            ("peaks", "Forme d'onde"),
                            ("thumbnail", "Miniature"),
                            ("wm_image", "Image filigranée"),
                            ("wm_audio", "Audio filigrané"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "params_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ready", "Prêt"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        upload_to=apps.files.models.derivative_path,
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=80)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="files.assetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("timestamp_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rect_x",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "rect_y",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "rect_w",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "rect_h",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="files.assetcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="files.assetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["project", "status"], name="files_asset_project_a345ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetversion",
            constraint=models.UniqueConstraint(
                fields=("asset", "number"), name="assetversion_unique_number_per_asset"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("file", ""), models.Q(("drive_file_id", ""), _negated=True)
                    ),
                    models.Q(
                        models.Q(("file", ""), _negated=True), ("drive_file_id", "")
                    ),
                    _connector="OR",
                ),
                name="assetversion_file_xor_drive",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetderivative",
            constraint=models.UniqueConstraint(
                fields=("version", "kind", "params_hash"),
                name="assetderivative_unique_per_version_kind_params",
            ),
        ),
    ]
