# Generated by Django 5.2.17 on 2026-09-22 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("projects", "0002_projectuserstate"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rrule", models.TextField()),
                ("dtstart", models.DateTimeField()),
                ("timezone", models.CharField(default="Europe/Zurich", max_length=64)),
                ("all_day", models.BooleanField(default=False)),
                ("generated_until", models.DateTimeField()),
                ("template", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_series",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("meeting", "RDV"),
                            ("live", "Date live"),
                            ("shooting", "Tournage"),
                            ("release", "Release"),
                            ("release_party", "Release party"),
                            ("class", "Cours"),
                            ("exam", "Examen"),
                            ("other", "Autre"),
                        ],
                        default="meeting",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=240)),
                ("prep_notes", models.TextField(blank=True)),
                ("report", models.TextField(blank=True)),
                ("decisions", models.JSONField(blank=True, default=list)),
                ("occurrence_at", models.DateTimeField(blank=True, null=True)),
                ("is_exception", models.BooleanField(default=False)),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="contacts.contact"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, related_name="events", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="workspaces.tag"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrences",
                        to="events.eventseries",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "id"],
                "indexes": [
                    models.Index(
                        fields=["project", "start"],
                        name="events_even_project_d074eb_idx",
                    ),
                    models.Index(fields=["start"], name="events_even_start_df0a74_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gte", models.F("start"))),
                        name="event_end_not_before_start",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("series__isnull", False)),
                        fields=("series", "occurrence_at"),
                        name="event_unique_occurrence_per_series",
                    ),
                ],
            },
        ),
    ]
