# Generated by Django 5.2.17 on 2026-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("meeting", "RDV"),
                    ("call", "Appel / visio"),
                    ("brief", "Brief"),
                    ("live", "Date live"),
                    ("rehearsal", "Répétition"),
                    ("soundcheck", "Balance"),
                    ("residency", "Résidence"),
                    ("studio", "Session studio"),
                    ("shooting", "Tournage"),
                    ("editing", "Montage"),
                    ("photoshoot", "Séance photo"),
                    ("release", "Release"),
                    ("release_party", "Release party"),
                    ("press", "Interview / presse"),
                    ("deadline", "Échéance"),
                    ("class", "Cours"),
                    ("exam", "Examen"),
                    ("submission", "Rendu"),
                    ("defense", "Soutenance"),
                    ("personal", "Personnel"),
                    ("other", "Autre"),
                ],
                default="meeting",
                max_length=20,
            ),
        ),
    ]
