/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description First call made by the front: sets the csrftoken cookie. */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Username + password login with two rate limits.
         *
         *     - per IP: DRF scoped throttle "login" (5/min);
         *     - per username: only FAILED attempts are counted (10/hour), so an attacker
         *       cannot lock a victim out just by spamming the endpoint with successes,
         *       and a legitimate user is never blocked by their own logins.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base for endpoints reachable without a session: CSRF + scoped throttle. */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base for endpoints reachable without a session: CSRF + scoped throttle. */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base for endpoints reachable without a session: CSRF + scoped throttle. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Who am I? Always 200, so that a signed-out visitor does not produce a
         *     401 error in the browser console. Also sets the CSRF cookie: it is the
         *     first call the front makes.
         */
        get: operations["auth_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base for endpoints reachable without a session: CSRF + scoped throttle. */
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_email_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklist-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Checklist items. `?task=` lists a checklist, `?pinned=true` feeds the
         *     "Todo épinglées" widget (open items of open tasks).
         */
        get: operations["checklist_items_list"];
        put?: never;
        /**
         * @description Checklist items. `?task=` lists a checklist, `?pinned=true` feeds the
         *     "Todo épinglées" widget (open items of open tasks).
         */
        post: operations["checklist_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklist-items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Checklist items. `?task=` lists a checklist, `?pinned=true` feeds the
         *     "Todo épinglées" widget (open items of open tasks).
         */
        delete: operations["checklist_items_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Checklist items. `?task=` lists a checklist, `?pinned=true` feeds the
         *     "Todo épinglées" widget (open items of open tasks).
         */
        patch: operations["checklist_items_partial_update"];
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Used by monitoring and by the deploy script: are Postgres and Redis up? */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pending invitations of a scope. Admins only (they contain e-mails). */
        get: operations["invitations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Pending invitations of a scope. Admins only (they contain e-mails). */
        delete: operations["invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{id}/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description New link, new 14 days. The previous link stops working. */
        post: operations["invitations_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Pending invitations of a scope. Admins only (they contain e-mails). */
        post: operations["invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/lookup/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public: what the acceptance page shows before sign-in or sign-up. */
        get: operations["invitations_lookup_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/me/avatar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["me_avatar_update"];
        post?: never;
        delete: operations["me_avatar_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memberships/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Who has access to a workspace or a project, and managing it.
         *
         *     - list: any real member of the scope (viewer and up). Shells see nothing.
         *     - create / update / delete: admins of the scope the membership is on.
         *       An admin may change or remove another admin, never the owner, and nobody
         *       can grant "owner" here (SPEC §6).
         *     - anyone may delete their own membership, except the owner.
         */
        get: operations["memberships_list"];
        put?: never;
        /**
         * @description Who has access to a workspace or a project, and managing it.
         *
         *     - list: any real member of the scope (viewer and up). Shells see nothing.
         *     - create / update / delete: admins of the scope the membership is on.
         *       An admin may change or remove another admin, never the owner, and nobody
         *       can grant "owner" here (SPEC §6).
         *     - anyone may delete their own membership, except the owner.
         */
        post: operations["memberships_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memberships/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Who has access to a workspace or a project, and managing it.
         *
         *     - list: any real member of the scope (viewer and up). Shells see nothing.
         *     - create / update / delete: admins of the scope the membership is on.
         *       An admin may change or remove another admin, never the owner, and nobody
         *       can grant "owner" here (SPEC §6).
         *     - anyone may delete their own membership, except the owner.
         */
        delete: operations["memberships_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Who has access to a workspace or a project, and managing it.
         *
         *     - list: any real member of the scope (viewer and up). Shells see nothing.
         *     - create / update / delete: admins of the scope the membership is on.
         *       An admin may change or remove another admin, never the owner, and nobody
         *       can grant "owner" here (SPEC §6).
         *     - anyone may delete their own membership, except the owner.
         */
        patch: operations["memberships_partial_update"];
        trace?: never;
    };
    "/api/project-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Project types of a workspace. Read: anyone in it. Write: admins. */
        get: operations["project_types_list"];
        put?: never;
        /** @description Project types of a workspace. Read: anyone in it. Write: admins. */
        post: operations["project_types_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-types/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Project types of a workspace. Read: anyone in it. Write: admins. */
        get: operations["project_types_retrieve"];
        put?: never;
        post?: never;
        /** @description Project types of a workspace. Read: anyone in it. Write: admins. */
        delete: operations["project_types_destroy"];
        options?: never;
        head?: never;
        /** @description Project types of a workspace. Read: anyone in it. Write: admins. */
        patch: operations["project_types_partial_update"];
        trace?: never;
    };
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Projects. There is no flat list: navigation uses the `tree` action. */
        post: operations["projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full project, or the reduced "shell" view of an ancestor. */
        get: operations["projects_retrieve"];
        put?: never;
        post?: never;
        /** @description Sub-project: editor of the PARENT. Root project: owner (D5). */
        delete: operations["projects_destroy"];
        options?: never;
        head?: never;
        /** @description Projects. There is no flat list: navigation uses the `tree` action. */
        patch: operations["projects_partial_update"];
        trace?: never;
    };
    "/api/projects/{id}/move/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Re-parent inside the workspace: admin here, editor on the target. */
        post: operations["projects_move_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/transfer-ownership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Root projects only: hand ownership to someone with direct access. */
        post: operations["projects_transfer_ownership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/tree/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every node the user can see, shells included, as a flat list. */
        get: operations["projects_tree_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Tags of a workspace.
         *
         *     Read: anyone in the workspace. Create: editors of the workspace or of any
         *     of its projects (they tag their own content). Rename / delete: workspace
         *     editors only, because it affects everybody's content.
         */
        get: operations["tags_list"];
        put?: never;
        /**
         * @description Tags of a workspace.
         *
         *     Read: anyone in the workspace. Create: editors of the workspace or of any
         *     of its projects (they tag their own content). Rename / delete: workspace
         *     editors only, because it affects everybody's content.
         */
        post: operations["tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Tags of a workspace.
         *
         *     Read: anyone in the workspace. Create: editors of the workspace or of any
         *     of its projects (they tag their own content). Rename / delete: workspace
         *     editors only, because it affects everybody's content.
         */
        get: operations["tags_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description Tags of a workspace.
         *
         *     Read: anyone in the workspace. Create: editors of the workspace or of any
         *     of its projects (they tag their own content). Rename / delete: workspace
         *     editors only, because it affects everybody's content.
         */
        delete: operations["tags_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Tags of a workspace.
         *
         *     Read: anyone in the workspace. Create: editors of the workspace or of any
         *     of its projects (they tag their own content). Rename / delete: workspace
         *     editors only, because it affects everybody's content.
         */
        patch: operations["tags_partial_update"];
        trace?: never;
    };
    "/api/task-comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Comments of a task (`?task=`). Writing needs the Commenter role;
         *     editing is for the author, deleting for the author or an admin.
         */
        get: operations["task_comments_list"];
        put?: never;
        /**
         * @description Comments of a task (`?task=`). Writing needs the Commenter role;
         *     editing is for the author, deleting for the author or an admin.
         */
        post: operations["task_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-comments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Comments of a task (`?task=`). Writing needs the Commenter role;
         *     editing is for the author, deleting for the author or an admin.
         */
        delete: operations["task_comments_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Comments of a task (`?task=`). Writing needs the Commenter role;
         *     editing is for the author, deleting for the author or an admin.
         */
        patch: operations["task_comments_partial_update"];
        trace?: never;
    };
    "/api/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin for viewsets whose objects belong to a project.
         *
         *     Declare roles with:
         *         read_role   = Role.VIEWER   (list, retrieve)
         *         write_role  = Role.EDITOR   (create, update, partial_update, destroy)
         *         action_roles = {"resolve": Role.COMMENTER}   (per-action overrides)
         *         finance = "" | "rw"  ("rw": reads need can_view_finance, writes
         *                               need can_edit_finance, on top of the role)
         *
         *     The model's default manager must come from ProjectScopedQuerySet.
         */
        get: operations["tasks_list"];
        put?: never;
        /**
         * @description Mixin for viewsets whose objects belong to a project.
         *
         *     Declare roles with:
         *         read_role   = Role.VIEWER   (list, retrieve)
         *         write_role  = Role.EDITOR   (create, update, partial_update, destroy)
         *         action_roles = {"resolve": Role.COMMENTER}   (per-action overrides)
         *         finance = "" | "rw"  ("rw": reads need can_view_finance, writes
         *                               need can_edit_finance, on top of the role)
         *
         *     The model's default manager must come from ProjectScopedQuerySet.
         */
        post: operations["tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin for viewsets whose objects belong to a project.
         *
         *     Declare roles with:
         *         read_role   = Role.VIEWER   (list, retrieve)
         *         write_role  = Role.EDITOR   (create, update, partial_update, destroy)
         *         action_roles = {"resolve": Role.COMMENTER}   (per-action overrides)
         *         finance = "" | "rw"  ("rw": reads need can_view_finance, writes
         *                               need can_edit_finance, on top of the role)
         *
         *     The model's default manager must come from ProjectScopedQuerySet.
         */
        get: operations["tasks_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description Mixin for viewsets whose objects belong to a project.
         *
         *     Declare roles with:
         *         read_role   = Role.VIEWER   (list, retrieve)
         *         write_role  = Role.EDITOR   (create, update, partial_update, destroy)
         *         action_roles = {"resolve": Role.COMMENTER}   (per-action overrides)
         *         finance = "" | "rw"  ("rw": reads need can_view_finance, writes
         *                               need can_edit_finance, on top of the role)
         *
         *     The model's default manager must come from ProjectScopedQuerySet.
         */
        delete: operations["tasks_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin for viewsets whose objects belong to a project.
         *
         *     Declare roles with:
         *         read_role   = Role.VIEWER   (list, retrieve)
         *         write_role  = Role.EDITOR   (create, update, partial_update, destroy)
         *         action_roles = {"resolve": Role.COMMENTER}   (per-action overrides)
         *         finance = "" | "rw"  ("rw": reads need can_view_finance, writes
         *                               need can_edit_finance, on top of the role)
         *
         *     The model's default manager must come from ProjectScopedQuerySet.
         */
        patch: operations["tasks_partial_update"];
        trace?: never;
    };
    "/api/tasks/{id}/move/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Drop a card in a column at a position. Warns if it is still blocked. */
        post: operations["tasks_move_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/blocker-candidates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Search for the "Bloquée par" field: tasks of the same root project
         *     that I can see and that would not create a loop.
         */
        get: operations["tasks_blocker_candidates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/avatar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Avatar image of any user, for signed-in users only. */
        get: operations["users_avatar_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Username autocompletion used to invite people.
         *
         *     Returns username, display name and avatar only, never e-mail or id.
         */
        get: operations["users_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        get: operations["workspaces_list"];
        put?: never;
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        post: operations["workspaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        get: operations["workspaces_retrieve"];
        put?: never;
        post?: never;
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        delete: operations["workspaces_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        patch: operations["workspaces_partial_update"];
        trace?: never;
    };
    "/api/workspaces/{id}/leave/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description CRUD on workspaces. Any signed-in user may create one and owns it. */
        post: operations["workspaces_leave_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{id}/transfer-ownership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description The owner hands the workspace over to a member and becomes admin. */
        post: operations["workspaces_transfer_ownership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A task blocking another one. For a blocker the user cannot see, only
         *     `id` and `is_open` are filled: enough for the padlock, nothing more.
         */
        Blocker: {
            id: number;
            visible: boolean;
            title: string | null;
            status: (components["schemas"]["TaskStatusEnum"] | components["schemas"]["NullEnum"]) | null;
            project_name: string | null;
            is_open: boolean;
        };
        BlockerCandidate: {
            id: number;
            title: string;
            status: components["schemas"]["TaskStatusEnum"];
            project_name: string;
        };
        Breadcrumb: {
            id: number;
            name: string;
            color: string;
            is_shell: boolean;
        };
        ChecklistItem: {
            readonly id: number;
            readonly task: number;
            title: string;
            done: boolean;
            pinned: boolean;
            position: number;
            /** Format: date-time */
            readonly done_at: string | null;
        };
        ChecklistItemRequest: {
            title: string;
            done?: boolean;
            pinned?: boolean;
            position?: number;
        };
        DirectMembership: {
            readonly id: number;
            role: components["schemas"]["RoleEnum"];
            can_view_finance: boolean;
            can_edit_finance: boolean;
        };
        /** @description One person with access to a scope: effective rights and where they come from. */
        EffectiveMember: {
            user: components["schemas"]["PublicUser"];
            role: components["schemas"]["RoleEnum"];
            can_view_finance: boolean;
            can_edit_finance: boolean;
            direct: components["schemas"]["DirectMembership"] | null;
            inherited_from: components["schemas"]["InheritedGrant"][];
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description * `viewer` - Lecteur
         *     * `commenter` - Commentateur
         *     * `editor` - Éditeur
         *     * `admin` - Admin
         * @enum {string}
         */
        GrantableRoleEnum: "viewer" | "commenter" | "editor" | "admin";
        InheritedGrant: {
            scope_type: components["schemas"]["ScopeTypeEnum"];
            scope_id: number;
            scope_name: string;
            role: components["schemas"]["RoleEnum"];
        };
        Invitation: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly workspace: number | null;
            readonly project: number | null;
            readonly role: components["schemas"]["RoleEnum"];
            readonly can_view_finance: boolean;
            readonly can_edit_finance: boolean;
            readonly invited_by: components["schemas"]["PublicUser"];
            /** Format: date-time */
            readonly expires_at: string;
            readonly is_pending: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        InvitationAcceptRequest: {
            token: string;
        };
        /** @description What the (public) acceptance page shows about an invitation. */
        InvitationLookup: {
            /** Format: email */
            email: string;
            scope_type: components["schemas"]["ScopeTypeEnum"];
            scope_name: string;
            role: components["schemas"]["RoleEnum"];
            invited_by: string | null;
            is_pending: boolean;
        };
        InviteResult: {
            kind: components["schemas"]["KindEnum"];
            detail: string;
        };
        /**
         * @description * `membership` - membership
         *     * `invitation` - invitation
         * @enum {string}
         */
        KindEnum: "membership" | "invitation";
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @description The signed-in user's own profile and preferences. */
        Me: {
            readonly id: number;
            /** Nom d'utilisateur */
            readonly username: string;
            /**
             * E-mail
             * Format: email
             */
            email: string;
            readonly email_verified: boolean;
            /** Prénom */
            first_name: string;
            /** Nom */
            last_name: string;
            readonly display_name: string;
            readonly avatar_url: string | null;
            phone: string;
            timezone: string;
            theme: components["schemas"]["ThemeEnum"];
            daily_digest_enabled: boolean;
            /** Format: time */
            daily_digest_time: string;
            email_on_mention: boolean;
            email_on_assignment: boolean;
        };
        /** @description Invite by username (existing account) or by e-mail. */
        MembershipCreateRequest: {
            workspace?: number;
            project?: number;
            username?: string;
            email?: string;
            role: components["schemas"]["GrantableRoleEnum"];
            can_view_finance?: boolean | null;
            can_edit_finance?: boolean | null;
        };
        MembershipUpdate: {
            readonly id: number;
            role: components["schemas"]["GrantableRoleEnum"];
            can_view_finance: boolean;
            can_edit_finance: boolean;
        };
        MoveProjectRequest: {
            parent: number | null;
        };
        MoveTaskRequest: {
            status: components["schemas"]["TaskStatusEnum"];
            position: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PaginatedTaskList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous: string | null;
            results: components["schemas"]["Task"][];
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            new_password: string;
        };
        PatchedChecklistItemRequest: {
            title?: string;
            done?: boolean;
            pinned?: boolean;
            position?: number;
        };
        /** @description The signed-in user's own profile and preferences. */
        PatchedMeRequest: {
            /**
             * E-mail
             * Format: email
             */
            email?: string;
            /** Prénom */
            first_name?: string;
            /** Nom */
            last_name?: string;
            phone?: string;
            timezone?: string;
            theme?: components["schemas"]["ThemeEnum"];
            daily_digest_enabled?: boolean;
            /** Format: time */
            daily_digest_time?: string;
            email_on_mention?: boolean;
            email_on_assignment?: boolean;
            current_password?: string;
        };
        PatchedMembershipUpdateRequest: {
            role?: components["schemas"]["GrantableRoleEnum"];
            can_view_finance?: boolean;
            can_edit_finance?: boolean;
        };
        /** @description Create / read / update a project the user has a real role on. */
        PatchedProjectRequest: {
            workspace?: number;
            parent?: number | null;
            name?: string;
            description?: string;
            type?: number;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            color?: string;
            tags?: number[];
            position?: number;
        };
        PatchedProjectTypeRequest: {
            workspace?: number;
            name?: string;
            position?: number;
        };
        PatchedTagRequest: {
            workspace?: number;
            name?: string;
            color?: string;
        };
        PatchedTaskCommentRequest: {
            body?: string;
        };
        PatchedTaskRequest: {
            project?: number;
            title?: string;
            description?: string;
            status?: components["schemas"]["TaskStatusEnum"];
            priority?: number;
            /** Format: date-time */
            start_at?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            all_day?: boolean;
            assignee_usernames?: string[];
            tags?: number[];
            blocked_by?: number[];
            rrule?: string;
        };
        /** @description Full view of a workspace, for its members. */
        PatchedWorkspaceRequest: {
            name?: string;
            color?: string;
        };
        /** @description Create / read / update a project the user has a real role on. */
        Project: {
            readonly id: number;
            workspace: number;
            parent: number | null;
            readonly depth: number;
            name: string;
            description: string;
            type: number;
            readonly type_name: string;
            status: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            start_date: string | null;
            /** Format: date */
            end_date: string | null;
            color: string;
            tags: number[];
            position: number;
            readonly temporal: components["schemas"]["TemporalEnum"];
            readonly end_overdue: boolean;
            readonly breadcrumb: components["schemas"]["Breadcrumb"][];
            readonly my_role: (components["schemas"]["RoleEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly can_view_finance: boolean;
            readonly can_edit_finance: boolean;
            readonly is_shell: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description One node of GET /api/projects/tree/ (a flat list; the front nests it).
         *
         *     For a SHELL node only id, workspace, parent, depth, name, color and
         *     is_shell are filled: every other field is null (SPECIFICATIONS §1.2).
         */
        ProjectNode: {
            id: number;
            workspace: number;
            parent: number | null;
            depth: number;
            name: string;
            color: string;
            is_shell: boolean;
            type: number | null;
            type_name: string | null;
            status: (components["schemas"]["ProjectStatusEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date */
            start_date: string | null;
            /** Format: date */
            end_date: string | null;
            temporal: (components["schemas"]["TemporalEnum"] | components["schemas"]["NullEnum"]) | null;
            end_overdue: boolean;
            tags: number[];
            position: number;
            my_role: (components["schemas"]["RoleEnum"] | components["schemas"]["NullEnum"]) | null;
            can_view_finance: boolean;
            can_edit_finance: boolean;
        };
        /** @description Create / read / update a project the user has a real role on. */
        ProjectRequest: {
            workspace?: number;
            parent?: number | null;
            name: string;
            description?: string;
            type?: number;
            status?: components["schemas"]["ProjectStatusEnum"];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            color?: string;
            tags?: number[];
            position?: number;
        };
        /**
         * @description * `idea` - Idée
         *     * `planned` - Planifié
         *     * `in_progress` - En cours
         *     * `to_validate` - À valider
         *     * `done` - Terminé
         *     * `cancelled` - Annulé
         *     * `archived` - Archivé
         * @enum {string}
         */
        ProjectStatusEnum: "idea" | "planned" | "in_progress" | "to_validate" | "done" | "cancelled" | "archived";
        ProjectType: {
            readonly id: number;
            workspace: number;
            name: string;
            position: number;
        };
        ProjectTypeRequest: {
            workspace: number;
            name: string;
            position?: number;
        };
        /**
         * @description The ONLY shape in which a user is exposed to other users (SPEC §4).
         *
         *     Never add e-mail, phone or id here: the search endpoint is open to every
         *     signed-in user.
         */
        PublicUser: {
            /** Nom d'utilisateur */
            username: string;
            readonly display_name: string;
            readonly avatar_url: string | null;
        };
        /**
         * @description The ONLY shape in which a user is exposed to other users (SPEC §4).
         *
         *     Never add e-mail, phone or id here: the search endpoint is open to every
         *     signed-in user.
         */
        PublicUserRequest: {
            /** Nom d'utilisateur */
            username: string;
        };
        Recurrence: {
            series: number;
            rrule: string;
            is_exception: boolean;
        };
        RegisterRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            first_name?: string;
            last_name?: string;
            accept_privacy: boolean;
            invitation?: string;
        };
        /**
         * @description * `viewer` - Lecteur
         *     * `commenter` - Commentateur
         *     * `editor` - Éditeur
         *     * `admin` - Admin
         *     * `owner` - Propriétaire
         * @enum {string}
         */
        RoleEnum: "viewer" | "commenter" | "editor" | "admin" | "owner";
        /**
         * @description * `workspace` - workspace
         *     * `project` - project
         * @enum {string}
         */
        ScopeTypeEnum: "workspace" | "project";
        /** @description Shape of GET /api/auth/session/: the profile, or null when signed out. */
        Session: {
            user: components["schemas"]["Me"] | null;
        };
        Tag: {
            readonly id: number;
            workspace: number;
            name: string;
            color: string;
        };
        TagRequest: {
            workspace: number;
            name: string;
            color?: string;
        };
        Task: {
            readonly id: number;
            project: number;
            readonly project_name: string;
            readonly project_color: string;
            title: string;
            description: string;
            status: components["schemas"]["TaskStatusEnum"];
            priority: number;
            /** Format: date-time */
            start_at: string | null;
            /** Format: date-time */
            due_at: string | null;
            all_day: boolean;
            readonly position: number;
            readonly assignees: components["schemas"]["PublicUser"][];
            tags: number[];
            blocked_by: number[];
            readonly blockers: components["schemas"]["Blocker"][];
            readonly is_blocked: boolean;
            readonly is_overdue: boolean;
            readonly checklist: components["schemas"]["ChecklistItem"][];
            readonly comments_count: number;
            readonly recurrence: components["schemas"]["Recurrence"] | null;
            /** Format: date-time */
            readonly completed_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        TaskComment: {
            readonly id: number;
            readonly task: number;
            readonly author: components["schemas"]["PublicUser"];
            body: string;
            readonly is_mine: boolean;
            /** Format: date-time */
            readonly edited_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        TaskCommentRequest: {
            body: string;
        };
        TaskRequest: {
            project: number;
            title: string;
            description?: string;
            status?: components["schemas"]["TaskStatusEnum"];
            priority?: number;
            /** Format: date-time */
            start_at?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            all_day?: boolean;
            assignee_usernames?: string[];
            tags?: number[];
            blocked_by?: number[];
            rrule?: string;
        };
        /**
         * @description * `todo` - À faire
         *     * `in_progress` - En cours
         *     * `to_validate` - À valider
         *     * `done` - Terminé
         *     * `cancelled` - Annulé
         * @enum {string}
         */
        TaskStatusEnum: "todo" | "in_progress" | "to_validate" | "done" | "cancelled";
        /**
         * @description * `past` - past
         *     * `current` - current
         *     * `upcoming` - upcoming
         * @enum {string}
         */
        TemporalEnum: "past" | "current" | "upcoming";
        /**
         * @description * `light` - Clair
         *     * `dark` - Sombre
         *     * `system` - Système
         * @enum {string}
         */
        ThemeEnum: "light" | "dark" | "system";
        TokenRequest: {
            token: string;
        };
        TransferOwnershipRequest: {
            username: string;
        };
        TransferProjectOwnershipRequest: {
            username: string;
        };
        /** @description Full view of a workspace, for its members. */
        Workspace: {
            readonly id: number;
            name: string;
            color: string;
            readonly my_role: (components["schemas"]["WorkspaceMyRoleEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly is_shell: boolean;
            readonly owner: components["schemas"]["PublicUser"] | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `viewer` - viewer
         *     * `commenter` - commenter
         *     * `editor` - editor
         *     * `admin` - admin
         *     * `owner` - owner
         * @enum {string}
         */
        WorkspaceMyRoleEnum: "viewer" | "commenter" | "editor" | "admin" | "owner";
        /** @description Full view of a workspace, for its members. */
        WorkspaceRequest: {
            name: string;
            color?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
                "multipart/form-data": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
                "multipart/form-data": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_verify_email_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checklist_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"][];
                };
            };
        };
    };
    checklist_items_create: {
        parameters: {
            query: {
                task: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemRequest"];
                "multipart/form-data": components["schemas"]["ChecklistItemRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
        };
    };
    checklist_items_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) checklist item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checklist_items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) checklist item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChecklistItemRequest"];
                "multipart/form-data": components["schemas"]["PatchedChecklistItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invitations_list: {
        parameters: {
            query?: {
                /** @description Portée : un projet */
                project?: number;
                /** @description Portée : un espace */
                workspace?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"][];
                };
            };
        };
    };
    invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) invitation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invitations_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) invitation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
                "multipart/form-data": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invitations_lookup_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationLookup"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMeRequest"];
                "multipart/form-data": components["schemas"]["PatchedMeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_avatar_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_avatar_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    memberships_list: {
        parameters: {
            query?: {
                /** @description Portée : un projet */
                project?: number;
                /** @description Portée : un espace */
                workspace?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveMember"][];
                };
            };
        };
    };
    memberships_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCreateRequest"];
                "multipart/form-data": components["schemas"]["MembershipCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResult"];
                };
            };
        };
    };
    memberships_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) membership. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memberships_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) membership. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMembershipUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedMembershipUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipUpdate"];
                };
            };
        };
    };
    project_types_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectType"][];
                };
            };
        };
    };
    project_types_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectTypeRequest"];
                "multipart/form-data": components["schemas"]["ProjectTypeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectType"];
                };
            };
        };
    };
    project_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectType"];
                };
            };
        };
    };
    project_types_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    project_types_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectTypeRequest"];
                "multipart/form-data": components["schemas"]["PatchedProjectTypeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectType"];
                };
            };
        };
    };
    projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRequest"];
                "multipart/form-data": components["schemas"]["ProjectRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectRequest"];
                "multipart/form-data": components["schemas"]["PatchedProjectRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_move_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveProjectRequest"];
                "multipart/form-data": components["schemas"]["MoveProjectRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_transfer_ownership_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) project. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferProjectOwnershipRequest"];
                "multipart/form-data": components["schemas"]["TransferProjectOwnershipRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_tree_list: {
        parameters: {
            query?: {
                include_archived?: boolean;
                /** @description Limiter à un espace */
                workspace?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectNode"][];
                };
            };
        };
    };
    tags_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
                "multipart/form-data": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    tags_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    tags_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tags_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) tag. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTagRequest"];
                "multipart/form-data": components["schemas"]["PatchedTagRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    task_comments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskComment"][];
                };
            };
        };
    };
    task_comments_create: {
        parameters: {
            query: {
                task: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCommentRequest"];
                "multipart/form-data": components["schemas"]["TaskCommentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskComment"];
                };
            };
        };
    };
    task_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    task_comments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task comment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskCommentRequest"];
                "multipart/form-data": components["schemas"]["PatchedTaskCommentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskComment"];
                };
            };
        };
    };
    tasks_list: {
        parameters: {
            query?: {
                assignee?: string;
                due_after?: string;
                due_before?: string;
                include_descendants?: boolean;
                no_date?: boolean;
                open?: boolean;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                overdue?: boolean;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                priority?: number;
                project?: number;
                search?: string;
                /**
                 * @description * `todo` - À faire
                 *     * `in_progress` - En cours
                 *     * `to_validate` - À valider
                 *     * `done` - Terminé
                 *     * `cancelled` - Annulé
                 */
                status?: ("cancelled" | "done" | "in_progress" | "to_validate" | "todo")[];
                tag?: number[];
                workspace?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTaskList"];
                };
            };
        };
    };
    tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
                "multipart/form-data": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_partial_update: {
        parameters: {
            query?: {
                /** @description Récurrence : cette occurrence, ou toutes les suivantes */
                scope?: "following" | "this";
            };
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskRequest"];
                "multipart/form-data": components["schemas"]["PatchedTaskRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_move_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequest"];
                "multipart/form-data": components["schemas"]["MoveTaskRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_blocker_candidates_list: {
        parameters: {
            query?: {
                assignee?: string;
                due_after?: string;
                due_before?: string;
                include_descendants?: boolean;
                no_date?: boolean;
                open?: boolean;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                overdue?: boolean;
                priority?: number;
                project?: number;
                q?: string;
                search?: string;
                /**
                 * @description * `todo` - À faire
                 *     * `in_progress` - En cours
                 *     * `to_validate` - À valider
                 *     * `done` - Terminé
                 *     * `cancelled` - Annulé
                 */
                status?: ("cancelled" | "done" | "in_progress" | "to_validate" | "todo")[];
                tag?: number[];
                task?: number;
                workspace?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockerCandidate"][];
                };
            };
        };
    };
    users_avatar_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
        };
    };
    users_search_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"][];
                };
            };
        };
    };
    workspaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
        };
    };
    workspaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceRequest"];
                "multipart/form-data": components["schemas"]["WorkspaceRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) workspace. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) workspace. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) workspace. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkspaceRequest"];
                "multipart/form-data": components["schemas"]["PatchedWorkspaceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    workspaces_leave_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) workspace. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_transfer_ownership_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) workspace. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipRequest"];
                "multipart/form-data": components["schemas"]["TransferOwnershipRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
}
