# Generated by Django 5.2.17 on 2026-09-22 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_projectuserstate"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("organization", models.CharField(blank=True, max_length=120)),
                ("job", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("instagram", models.CharField(blank=True, max_length=60)),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="contacts", to="workspaces.tag"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "organization", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_label", models.CharField(blank=True, max_length=80)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="contacts.contact",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["contact__last_name", "contact__first_name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["workspace", "last_name", "first_name"],
                name="contacts_co_workspa_98d612_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcontact",
            constraint=models.UniqueConstraint(
                fields=("project", "contact"), name="projectcontact_unique_pair"
            ),
        ),
    ]
