# Generated by Django 5.2.17 on 2026-09-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_seed_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="budget_lines",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="recurring_expenses",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transactions",
                to="finance.category",
            ),
        ),
    ]
