# Generated by Django 5.2.17 on 2026-09-21 16:10

import apps.accounts.models
import datetime
import django.core.validators
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "Ce nom d'utilisateur est déjà pris."
                        },
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="3 à 30 caractères : lettres sans accent, chiffres, point, tiret ou underscore.",
                                regex="^[A-Za-z0-9_.-]{3,30}$",
                            )
                        ],
                        verbose_name="nom d'utilisateur",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Un compte existe déjà avec cet e-mail."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="e-mail",
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("timezone", models.CharField(default="Europe/Zurich", max_length=64)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("daily_digest_enabled", models.BooleanField(default=True)),
                ("daily_digest_time", models.TimeField(default=datetime.time(8, 0))),
                ("last_digest_sent_on", models.DateField(blank=True, null=True)),
                ("email_on_mention", models.BooleanField(default=True)),
                ("email_on_assignment", models.BooleanField(default=True)),
                ("privacy_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("username"),
                        name="user_username_ci_unique",
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.FaiblegraineUserManager()),
            ],
        ),
    ]
