# Generated by Django 5.2.17 on 2026-09-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_project_drive_account_project_drive_folder_url_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("created", "Création"),
                            ("updated", "Modification"),
                            ("status_changed", "Statut"),
                            ("deleted", "Suppression"),
                            ("shared", "Partage"),
                            ("access_changed", "Droits"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=30)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_label", models.CharField(max_length=240)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="activity_ac_project_e539e5_idx",
                    ),
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="activity_ac_workspa_7f542a_idx",
                    ),
                ],
            },
        ),
    ]
