# Generated by Django 5.2.17 on 2026-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("structure", "Artistes & structures"),
                    ("music", "Production musicale"),
                    ("video", "Audiovisuel"),
                    ("live", "Live & événements"),
                    ("release", "Sortie & promotion"),
                    ("communication", "Communication & contenu"),
                    ("admin", "Administratif & financement"),
                    ("studies", "Études"),
                    ("client", "Mandats & clients"),
                    ("personal", "Personnel"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
