# Generated by Django 5.2.17 on 2026-09-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_displayed", models.BooleanField(default=False)),
                ("is_target", models.BooleanField(default=False)),
                ("sync_cursor", models.TextField(blank=True)),
                ("watch_channel_id", models.CharField(blank=True, max_length=64)),
                ("watch_resource_id", models.CharField(blank=True, max_length=200)),
                ("watch_token_hash", models.CharField(blank=True, max_length=64)),
                ("watch_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="integrations.oauthaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExternalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=300)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("etag", models.CharField(blank=True, max_length=200)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="integrations.externalcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "id"],
            },
        ),
        migrations.CreateModel(
            name="SyncMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[("task", "Tâche"), ("event", "Événement")],
                        max_length=10,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("external_id", models.CharField(max_length=300)),
                ("etag", models.CharField(blank=True, max_length=200)),
                ("pushed_hash", models.CharField(blank=True, max_length=64)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("external_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Synchronisé"), ("detached", "Détaché")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="integrations.externalcalendar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        choices=[
                            ("local", "Faiblegraine"),
                            ("external", "Calendrier externe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="integrations.syncmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="externalcalendar",
            constraint=models.UniqueConstraint(
                fields=("account", "external_id"), name="externalcalendar_unique_id"
            ),
        ),
        migrations.AddIndex(
            model_name="externalevent",
            index=models.Index(
                fields=["calendar", "start"], name="integration_calenda_a8087e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalevent",
            constraint=models.UniqueConstraint(
                fields=("calendar", "external_id"), name="externalevent_unique_id"
            ),
        ),
        migrations.AddIndex(
            model_name="syncmapping",
            index=models.Index(
                fields=["calendar", "external_id"],
                name="integration_calenda_aa89ee_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncmapping",
            constraint=models.UniqueConstraint(
                fields=("calendar", "object_type", "object_id"),
                name="syncmapping_unique_object",
            ),
        ),
    ]
